<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SpawnDev.WebTorrent\SpawnDev.WebTorrent.csproj" />
		<ProjectReference Include="..\SpawnDev.WebTorrent.Demo.Shared\SpawnDev.WebTorrent.Demo.Shared.csproj" />
		<ProjectReference Include="..\..\..\SpawnDev.UnitTesting\SpawnDev.UnitTesting\SpawnDev.UnitTesting.Desktop\SpawnDev.UnitTesting.Desktop.csproj" />
	</ItemGroup>

</Project>
